# -*- coding: utf-8 -*-
"""pyvis_sample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/ItaloNardy/NetworkAnalysis_Pyvis-Streamlit/blob/main/pyvis_sample.ipynb
"""

import subprocess
import sys

# Automatically install pyvis if not already installed
subprocess.check_call([sys.executable, "-m", "pip", "install", "pyvis"])


from operator import itemgetter
from pyvis import network as net
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import seaborn as sns



nx.__version__

got_net=net.Network(height='800px', width='100%',heading='', notebook=True, cdn_resources='remote')

# set the physics layout of the network
got_net.barnes_hut()
got_data = pd.read_csv("../content/got-edges.csv")

sources = got_data['Source']
targets = got_data['Target']
weights = got_data['Weight']

edge_data = zip(sources, targets, weights)

for e in edge_data:
                src = e[0]
                dst = e[1]
                w = e[2]

                got_net.add_node(src, src, title=src)
                got_net.add_node(dst, dst, title=dst)
                got_net.add_edge(src, dst, value=w)

neighbor_map = got_net.get_adj_list()

# add neighbor data to node hover data
for node in got_net.nodes:
                node["title"] += " Neighbors:<br>" + "<br>".join(neighbor_map[node["id"]])
                node["value"] = len(neighbor_map[node["id"]])

g.repulsion()
g.show_buttons(filter_=['physics'])
got_net.show("gameofthrones.html")
display(HTML('gameofthrones.html'))

"""#END"""